---
- hosts: "ncv"
  serial: 1
  remote_user: vagrant
  become: yes
  gather_facts: false
  tasks:
  - name: Restart netplugin service
    service: name=netplugin state=restarted
  - name: Restart netmaster service
    service: name=netmaster state=restarted
  - name: Restart aci_gw service
    service: name=aci_gw state=restarted

- hosts: "all"
  serial: 1
  remote_user: vagrant
  become: yes
  gather_facts: false
  tasks:
  - name: Restart netplugin service
    service: name=netplugin state=restarted
